name: election-pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyter
  - nbconvert
  - pandas
  - numpy
  - requests
  - scipy
  - matplotlib
  - scikit-learn
  - pip
  - pip:
    - snakemake
